# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 23.9.1 # Use the latest version
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: v7.1.1 # Use the latest version
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-added-large-files
      - id: detect-aws-credentials
      - id: remove-tabs
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-yaml
