# Generated by Django 5.1.4 on 2024-12-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=50),
        ),
    ]
